# Generated by Django 4.2.16 on 2024-09-09 10:06

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.CharField(db_column='game_id', db_index=True)),
                ('userId', models.IntegerField(db_column='user_id')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('state', models.CharField()),
                ('createTime', models.IntegerField(db_column='create_time', db_index=True, default=time.time)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.CharField(default='945b96c9-68f4-4400-9afd-b03dfe849810', primary_key=True, serialize=False)),
                ('userId', models.IntegerField(db_column='user_id', db_index=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('mineDensity', models.SmallIntegerField(db_column='mine_density')),
                ('mineCoordinates', models.JSONField(db_column='mine_coordinates', default=list)),
                ('state', models.SmallIntegerField(null=True)),
                ('createTime', models.IntegerField(db_column='create_time', db_index=True, default=time.time)),
            ],
        ),
    ]
