# Generated by Django 4.2.16 on 2024-09-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='id',
            field=models.CharField(default='58e7812e-64a7-4a11-b236-9ea60b58cf60', primary_key=True, serialize=False),
        ),
    ]
