# Generated by Django 4.2.16 on 2024-09-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0002_alter_gamesession_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='id',
            field=models.CharField(default='4eb735a2-c446-47d7-884b-32eab9e38008', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='state',
            field=models.CharField(null=True),
        ),
    ]
